from abc import ABC, abstractmethod
from typing import Optional
from app.domain.entities.user import User
from app.domain.entities.character import Character, CharacterStats
from app.domain.entities.event import Event, EventResult
from app.domain.entities.world import City, Job, WorldState


class IUserRepository(ABC):
    @abstractmethod
    async def get_by_id(self, user_id: int) -> Optional[User]: ...
    @abstractmethod
    async def get_by_openid(self, openid: str) -> Optional[User]: ...
    @abstractmethod
    async def create(self, user: User) -> User: ...
    @abstractmethod
    async def update(self, user: User) -> User: ...


class ICharacterRepository(ABC):
    @abstractmethod
    async def get_by_id(self, character_id: int) -> Optional[Character]: ...
    @abstractmethod
    async def get_by_user_id(self, user_id: int) -> list[Character]: ...
    @abstractmethod
    async def create(self, character: Character) -> Character: ...
    @abstractmethod
    async def update(self, character: Character) -> Character: ...
    @abstractmethod
    async def get_stats(self, character_id: int) -> Optional[CharacterStats]: ...
    @abstractmethod
    async def update_stats(self, character_id: int, stats: CharacterStats) -> CharacterStats: ...


class IEventRepository(ABC):
    @abstractmethod
    async def get_by_id(self, event_id: int) -> Optional[Event]: ...
    @abstractmethod
    async def get_by_stage(self, stage: str) -> list[Event]: ...
    @abstractmethod
    async def get_results(self, event_id: int) -> list[EventResult]: ...
    @abstractmethod
    async def get_result_by_choice(self, event_id: int, choice_index: int) -> Optional[EventResult]: ...


class IWorldRepository(ABC):
    @abstractmethod
    async def get_cities(self) -> list[City]: ...
    @abstractmethod
    async def get_city_by_id(self, city_id: int) -> Optional[City]: ...
    @abstractmethod
    async def get_jobs(self) -> list[Job]: ...
    @abstractmethod
    async def get_world_state(self, year: int) -> Optional[WorldState]: ...
